---
- name: clone chinachu repo
  git:
    repo=git://github.com/kanreisa/Chinachu.git
    dest={{ chinachu_app_dir }}
    accept_hostkey=true
  tags: chinachu-update

#- name: create symlink
#  file: src={{ chinachu_app_dir }}/chinachu dest={{ chinachu_symlink }} state=link
#  tags: chinachu

- name: copy chinachu_installer.sh
  copy: src=chinachu_installer.sh dest={{ chinachu_app_dir }} mode=0744
  tags: chinachu-update

- name: install chinachu
  command:
    ./chinachu_installer.sh
    chdir={{ chinachu_app_dir }}
  tags: chinachu-update

- name: chinachu config
  template:
    src=config.json.j2
    dest={{ chinachu_app_dir }}/config.json
  tags: chinachu-config

- name: create chinachu recorded directory
  file:
    path={{ chinachu_recorded_dir }}
    state=directory
  tags: chinachu-config

- name: create empty rules.json
  shell: echo "[]" > {{ chinachu_app_dir }}/rules.json
  tags: chinachu-rules

- name: copy chinachu-operator unit file
  copy:
    src=chinachu-operator.service
    dest=/lib/systemd/system/chinachu-operator.service
    mode=644
    owner=root
    group=root
  sudo: yes
  tags: chinachu-start

- name: copy chinachu-wui unit file
  copy:
    src=chinachu-wui.service
    dest=/lib/systemd/system/chinachu-wui.service
    mode=644
    owner=root
    group=root
  sudo: yes
  tags: chinachu-start

- name: reload systemd
  command: systemctl daemon-reload
  sudo: yes
  tags: chinachu-start

- name: start chinachu-operator
  service:
    name=chinachu-operator
    state=started
    enabled=yes
  sudo: yes
  tags: chinachu-start

- name: start chinachu-wui
  service:
    name=chinachu-wui
    state=started
    enabled=yes
  sudo: yes
  tags: chinachu-start
